### ISSUE TITLE
Update to Swift 3

### ISSUE THREAD

**Issue by peterdk** [shnhrrsn/ImagePalette#3]
It would be great if this could be converted to Swift 3.
I am not an expert on Swift unfortunately, so some conversion choices are a bit hard to make myself.

**Comment by shnhrrsn** [comment]
I'll see if I can get it updated soon

**Comment by peterdk** [comment]
Ok, great! I had some issues with `UnsafePointers` that I did not understand. Thanks for the work, the library is very useful!

**Comment by shnhrrsn** [comment]
@peterdk just published 0.1.0 with Swift 3 support

**Comment by peterdk** [comment]
Great! Xcode 8.3 doesnt support Swift 2 anymore, so thank you!!
